import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "admin",
      email: "jchoudhary1892@gmail.com",
      password: bcrypt.hashSync("12345"),
      isAdmin: true,
    },
    {
      name: "user1",
      email: "user@gmail.com",
      password: bcrypt.hashSync("12345"),
      isAdmin: false,
    },
  ],
  products: [
    // Men's Shirts
    {
      slug: "Twill Cotton Shirt",
      name: "Twill Cotton Shirt",
      category: "Men's Shirts",
      brand: "Brand 1",
      image1: "/assets/images/products/jacket-3.webp",
      image2: "/assets/images/products/jacket-4.webp",
      showcaseBadge: "sale",
      discountPrice: 385.0,
      price: 799.0,
      rating: 4.5,
      numReviews: 10,
      description: "high quality material",
      countInStock: 100,
    },
    {
      slug: "Poplin Shirt 132*72 Cotton Laffer Finish",
      name: "Poplin Shirt 132*72 Cotton Laffer Finish",
      category: "Men's Shirts",
      brand: "Brand 2",
      image1: "/assets/images/products/shirt-1.jpg",
      image2: "/assets/images/products/shirt-2.jpeg",
      showcaseBadge: "sale",
      discountPrice: 320.0,
      price: 599.0,
      rating: 4.0,
      numReviews: 10,
      description: "high quality material",
      countInStock: 100,
    },
    {
      slug: "Indigo Twill Checks",
      name: "Indigo Twill Checks",
      category: "Men's Shirts",
      brand: "Brand 3",
      image1: "/assets/images/products/jacket-5.webp",
      image2: "/assets/images/products/jacket-6.webp",
      showcaseBadge: "sale",
      discountPrice: 435.0,
      price: 899.0,
      rating: 3.0,
      numReviews: 10,
      description: "high quality material",
      countInStock: 100,
    },

    // Men's Pants
    {
      slug: "Classic Denim Jeans",
      name: "Classic Denim Jeans",
      category: "Men's Pants",
      brand: "Brand 1",
      image1: "/assets/images/products/clothes-3.webp",
      image2: "/assets/images/products/clothes-4.jpeg",
      showcaseBadge: "new",
      discountPrice: 550.0,
      price: 799.0,
      rating: 4.2,
      numReviews: 15,
      description: "comfortable fit denim jeans",
      countInStock: 75,
    },
    {
      slug: "Formal Trousers",
      name: "Formal Trousers",
      category: "Men's Pants",
      brand: "Brand 2",
      image1: "/assets/images/products/shoe-2.jpg",
      image2: "/assets/images/products/shoe-2_1.jpeg",
      showcaseBadge: "sale",
      discountPrice: 450.0,
      price: 650.0,
      rating: 4.0,
      numReviews: 12,
      description: "professional formal trousers",
      countInStock: 90,
    },

    // Women's Clothing
    {
      slug: "Elegant Floral Dress",
      name: "Elegant Floral Dress",
      category: "Women's Dresses",
      brand: "Brand 1",
      image1: "/assets/images/products/shirt-6.jpg",
      image2: "/assets/images/products/shirt-6_1.jpg",
      showcaseBadge: "new",
      discountPrice: 485.0,
      price: 750.0,
      rating: 4.7,
      numReviews: 20,
      description: "beautiful floral pattern dress",
      countInStock: 60,
    },
    {
      slug: "Women's Cotton Blouse",
      name: "Women's Cotton Blouse",
      category: "Women's Tops",
      brand: "Brand 2",
      image1: "/assets/images/products/jacket-3.webp",
      image2: "/assets/images/products/jacket-4.webp",
      showcaseBadge: "sale",
      discountPrice: 295.0,
      price: 450.0,
      rating: 4.3,
      numReviews: 18,
      description: "soft cotton blouse for everyday wear",
      countInStock: 120,
    },
    {
      slug: "Women's Skinny Jeans",
      name: "Women's Skinny Jeans",
      category: "Women's Pants",
      brand: "Brand 3",
      image1: "/assets/images/products/shirt-1.jpg",
      image2: "/assets/images/products/shirt-2.jpeg",
      showcaseBadge: "popular",
      discountPrice: 385.0,
      price: 599.0,
      rating: 4.4,
      numReviews: 25,
      description: "trendy skinny fit jeans",
      countInStock: 85,
    },

    // Children's Clothing
    {
      slug: "Kids Cotton T-Shirt",
      name: "Kids Cotton T-Shirt",
      category: "Children's Tops",
      brand: "Brand 1",
      image1: "/assets/images/products/jacket-5.webp",
      image2: "/assets/images/products/jacket-6.webp",
      showcaseBadge: "new",
      discountPrice: 199.0,
      price: 299.0,
      rating: 4.6,
      numReviews: 30,
      description: "comfortable cotton t-shirt for kids",
      countInStock: 150,
    },
    {
      slug: "Children's Denim Shorts",
      name: "Children's Denim Shorts",
      category: "Children's Shorts",
      brand: "Brand 2",
      image1: "/assets/images/products/clothes-3.webp",
      image2: "/assets/images/products/clothes-4.jpeg",
      showcaseBadge: "sale",
      discountPrice: 225.0,
      price: 350.0,
      rating: 4.1,
      numReviews: 22,
      description: "durable denim shorts for children",
      countInStock: 100,
    },
    {
      slug: "Kids Summer Dress",
      name: "Kids Summer Dress",
      category: "Children's Dresses",
      brand: "Brand 3",
      image1: "/assets/images/products/shoe-2.jpg",
      image2: "/assets/images/products/shoe-2_1.jpeg",
      showcaseBadge: "popular",
      discountPrice: 275.0,
      price: 425.0,
      rating: 4.8,
      numReviews: 35,
      description: "colorful summer dress for kids",
      countInStock: 80,
    },

    // Shoes
    {
      slug: "Men's Running Shoes",
      name: "Men's Running Shoes",
      category: "Men's Shoes",
      brand: "Brand 1",
      image1: "/assets/images/products/shirt-6.jpg",
      image2: "/assets/images/products/shirt-6_1.jpg",
      showcaseBadge: "new",
      discountPrice: 799.0,
      price: 1199.0,
      rating: 4.5,
      numReviews: 40,
      description: "comfortable running shoes",
      countInStock: 45,
    },
    {
      slug: "Women's Heels",
      name: "Women's Heels",
      category: "Women's Shoes",
      brand: "Brand 2",
      image1: "/assets/images/products/jacket-3.webp",
      image2: "/assets/images/products/jacket-4.webp",
      showcaseBadge: "sale",
      discountPrice: 650.0,
      price: 950.0,
      rating: 4.2,
      numReviews: 28,
      description: "elegant heels for special occasions",
      countInStock: 35,
    },
  ],
};

export default data;
