const data = {
  products: [
    {
      _id: 1,
      name: "Mens Winter Leathers Jackets",
      category: "jacket",
      image1: "./assets/images/products/jacket-3.jpg",
      image2: "./assets/images/products/jacket-4.jpg",
      showcaseBadge: "sale",
      discountPrice: 4800.0,
      price: 7500.0,
      //   discountPercent: (.price - discountPrice) / price * 100 ,
      rating: 4.5,
      numReviews: 10,
      description: "high quality material",
    },
    {
      _id: 2,
      name: "Pure Garment Dyed Cotton Shirt",
      category: "shirt",
      image1: "./assets/images/products/shirt-1.jpg",
      image2: "./assets/images/products/shirt-2.jpg",
      showcaseBadge: "sale",
      discountPrice: 4500.0,
      price: 5600.0,
      rating: 4.0,
      numReviews: 10,
      description: "high quality material",
    },
    {
      _id: 3,
      name: "MEN Yarn Fleece Full-Zip Jacket",
      category: "Jacket",
      image1: "./assets/images/products/jacket-5.jpg",
      image2: "./assets/images/products/jacket-6.jpg",
      showcaseBadge: "sale",
      discountPrice: 5800.0,
      price: 6500.0,
      rating: 3.0,
      numReviews: 10,
      description: "high quality material",
    },
    {
      _id: 4,
      name: "Black Floral Wrap Mini Skirt",
      category: "skirt",
      image1: "./assets/images/products/clothes-3.jpg",
      image2: "./assets/images/products/clothes-4.jpg",
      showcaseBadge: "sale",
      discountPrice: 2500.0,
      price: 3500.0,
      rating: 2.0,
      numReviews: 10,
      description: "high quality material",
    },
    {
      _id: 5,
      name: "Casual Men's Brown shoes",
      category: "shoes",
      image1: "./assets/images/products/shoe-2.jpg",
      image2: "./assets/images/products/shoe-2_1.jpg",
      showcaseBadge: "sale",
      discountPrice: 9900.0,
      price: 10500.0,
      rating: 1.0,
      numReviews: 10,
      description: "high quality material",
    },
  ],
};

export default data;
