const data = {
  products: [
    {
      _id: "1",
      slug: "Twill Cotton Shirt",
      name: "Twill Cotton Shirt",
      category: "Shirts",
      image1: "/assets/images/products/jacket-3.webp",
      image2: "/assets/images/products/jacket-4.webp",
      showcaseBadge: "sale",
      discountPrice: 385.0,
      price: 799.0,
      rating: 4.5,
      numReviews: 10,
      description: "high quality material",
      countInStock: 0,
    },
    {
      _id: "2",
      slug: "Poplin Shirt 132*72 Cotton Laffer Finish",
      name: "Poplin Shirt 132*72 Cotton Laffer Finish",
      category: "Shirts",
      image1: "/assets/images/products/shirt-1.jpg",
      image2: "/assets/images/products/shirt-2.jpeg",
      showcaseBadge: "sale",
      discountPrice: 320.0,
      price: 599.0,
      rating: 4.0,
      numReviews: 10,
      description: "high quality material",
      countInStock: 100,
    },
    {
      _id: "3",
      slug: "Indigo Twill Checks",
      name: "Indigo Twill Checks",
      category: "Shirts",
      image1: "/assets/images/products/jacket-5.webp",
      image2: "/assets/images/products/jacket-6.webp",
      showcaseBadge: "sale",
      discountPrice: 435.0,
      price: 899.0,
      rating: 3.0,
      numReviews: 10,
      description: "high quality material",
      countInStock: 100,
    },
    {
      _id: "4",
      slug: "Indigo Twill Checks With Double Pocket Snap Button",
      name: "Indigo Twill Checks With Double Pocket Snap Button",
      category: "Shirts",
      image1: "/assets/images/products/clothes-3.webp",
      image2: "/assets/images/products/clothes-4.jpeg",
      showcaseBadge: "sale",
      discountPrice: 440.0,
      price: 899.0,
      rating: 2.0,
      numReviews: 10,
      description: "high quality material",
      countInStock: 100,
    },
    {
      _id: "5",
      slug: "30's Twill Shirt",
      name: "30's Twill Shirt",
      category: "Shirts",
      image1: "/assets/images/products/shoe-2.jpg",
      image2: "/assets/images/products/shoe-2_1.jpeg",
      showcaseBadge: "sale",
      discountPrice: 350.0,
      price: 550.0,
      rating: 1.0,
      numReviews: 10,
      description: "high quality material",
      countInStock: 100,
    },
    {
      _id: "6",
      slug: "Twill Double Pocket",
      name: "Twill Double Pocket",
      category: "Shirts",
      image1: "/assets/images/products/shirt-6.jpg",
      image2: "/assets/images/products/shirt-6_1.jpg",
      showcaseBadge: "sale",
      discountPrice: 385.0,
      price: 650.0,
      rating: 1.0,
      numReviews: 10,
      description: "high quality material",
      countInStock: 100,
    },
  ],
};

export default data;
